<?xml version="1.0" encoding="utf-8"?><Database Name="Concordation" Class="DBConDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SHAKEDAV-PC\CONCORDATION;Initial Catalog=Concordation;Integrated Security=True" SettingsObjectName="concordanceapConcordationDataSetTableAdaptersp.Properties.Settings" SettingsPropertyName="ConcordationConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.addAttributes" Method="addAttributes">
    <Parameter Name="docID" Type="System.Int32" DbType="Int" />
    <Parameter Name="attValue" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="attType" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetSearchWord" Method="GetSearchWord">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetSearchWordResult">
      <Column Name="Word" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LineNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WordNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertWord" Method="InsertWord">
    <Parameter Name="Word" Parameter="word" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Line" Parameter="line" Type="System.Int32" DbType="Int" />
    <Parameter Name="WordNum" Parameter="wordNum" Type="System.Int32" DbType="Int" />
    <Parameter Name="DocID" Parameter="docID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ContextWords" Method="ContextWords">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="ContextWordsResult">
      <Column Name="Context" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Line" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Word Number" Member="Word_Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Document" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTaggedWords" Method="GetTaggedWords">
    <ElementType Name="GetTaggedWordsResult">
      <Column Name="Word" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddTag" Method="AddTag">
    <Parameter Name="TagName" Parameter="tagName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTotalAppearances" Method="GetTotalAppearances">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetContainingDocs" Method="GetContainingDocs">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetContainingTags" Method="GetContainingTags">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetDocsOfWord" Method="GetDocsOfWord">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetDocsOfWordResult">
      <Column Name="value" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTagsofWord" Method="GetTagsofWord">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetTagsofWordResult">
      <Column Name="Word" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TagWord" Method="TagWord">
    <Parameter Name="Word" Parameter="word" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TagName" Parameter="tagName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddRelation" Method="AddRelation">
    <Parameter Name="Relation" Parameter="relation" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetContainingRelations" Method="GetContainingRelations">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getRelationsOfWord" Method="getRelationsOfWord">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="getRelationsOfWordResult">
      <Column Name="word1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RelationName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="word2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetWordID" Method="GetWordID">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddExpression" Method="AddExpression">
    <Parameter Name="wordid" Type="System.Int32" DbType="Int" />
    <Parameter Name="Expression" Parameter="expression" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="wordNum" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetExpressions" Method="GetExpressions">
    <ElementType Name="GetExpressionsResult">
      <Column Name="expression" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetContainingExpressions" Method="GetContainingExpressions">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertWord2" Method="InsertWord2">
    <Parameter Name="Word" Parameter="word" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Line" Parameter="line" Type="System.Int32" DbType="Int" />
    <Parameter Name="WordNum" Parameter="wordNum" Type="System.Int32" DbType="Int" />
    <Parameter Name="DocID" Parameter="docID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetExpressionsOfWord" Method="GetExpressionsOfWord">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetExpressionsOfWordResult">
      <Column Name="Expression" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDocType" Method="GetDocType">
    <Parameter Name="typeName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetDocAttrs" Method="GetDocAttrs">
    <Parameter Name="doctype" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetDocAttrsResult">
      <Column Name="AttName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTypeAtts" Method="GetTypeAtts">
    <Parameter Name="docTypeID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTypeAttsResult">
      <Column Name="AttName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getDocID" Method="getDocID">
    <Parameter Name="fileName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAttTypeID" Method="GetAttTypeID">
    <Parameter Name="attName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetExistingAttsfordoc" Method="GetExistingAttsfordoc">
    <Parameter Name="docID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetExistingAttsfordocResult">
      <Column Name="[Attribute Name]" Member="Attribute_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Attribute" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertDocument" Method="InsertDocument">
    <Parameter Name="TypeID" Parameter="typeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FileName" Parameter="fileName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAllWords" Method="GetAllWords">
    <ElementType Name="GetAllWordsResult">
      <Column Name="Word" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LineNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WordNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RelateWords" Method="RelateWords">
    <Parameter Name="word1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="relation" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="word2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="isDual" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddSearchNumber" Method="AddSearchNumber">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetWordSearches" Method="GetWordSearches">
    <Parameter Name="word" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetWordByLineAndNum" Method="GetWordByLineAndNum">
    <Parameter Name="LineNum" Parameter="lineNum" Type="System.Int32" DbType="Int" />
    <Parameter Name="wordNum" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetWordByLineAndNumResult">
      <Column Name="word" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LineNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WordNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetWordByTagName" Method="GetWordByTagName">
    <Parameter Name="Tag" Parameter="tag" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetWordByTagNameResult">
      <Column Name="word" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ExportTable" Method="ExportTable">
    <Parameter Name="TableName" Parameter="tableName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="filename" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>